#lang racket
(require "common.rkt")

; Find how many distinct terms are generated by a^b, 2 <= a <= 100, 2 <= b <= 100.

(define (solve)
  
  (define (make-pairs n)
    (define v (range 2 n))
    (cartesian-product v v))
  
  (define (seq-len n) 
    (length 
     (remove-duplicates 
      (map (lambda (x) (apply expt x)) (make-pairs n)))))
  
  (seq-len 100))

(provide solve)